server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: INFO
    org.springframework.security: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: task-service-all
          uri: http://${TASK_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/api/tasks/get/all
            - Method=GET
        - id: task-service-get
          uri: http://${TASK_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/api/tasks/get/**
            - Method=GET
        - id: task-service-create
          uri: http://${TASK_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/api/tasks/add
            - Method=POST
        - id: task-service-update
          uri: http://${TASK_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/api/tasks/update/**
            - Method=PUT
        - id: task-service-delete
          uri: http://${TASK_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/api/tasks/delete/**
            - Method=DELETE
        - id: department-service-all
          uri: http://${TEAM_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/api/dep/get/all
            - Method=GET
        - id: department-service-create
          uri: http://${TEAM_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/api/dep/add
            - Method=POST
        - id: department-service-get
          uri: http://${TEAM_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/api/dep/get/**
            - Method=GET
        - id: member-service-all
          uri: http://${TEAM_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/api/members/get/all
            - Method=GET
        - id: member-service-create
          uri: http://${TEAM_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/api/members/add
            - Method=POST
        - id: member-service-get
          uri: http://${TEAM_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/api/members/get/**
            - Method=GET
        - id: member-service-update
          uri: http://${TEAM_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/api/members/update/**
            - Method=PUT
        - id: member-service-delete
          uri: http://${TEAM_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/api/members/delete/**
            - Method=DELETE
        - id: member-service-to-team
          uri: http://${TEAM_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/api/members/addMemberToTeam/**
            - Method=POST
        - id: member-service-team-remove
          uri: http://${TEAM_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/api/members/remove-from-team
            - Method=DELETE
        - id: member-team-create
          uri: http://${TEAM_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/api/teams/add
            - Method=POST
        - id: member-team-all
          uri: http://${TEAM_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/api/teams/get/all
            - Method=GET
        - id: member-team-get
          uri: http://${TEAM_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/api/teams/get/**
            - Method=GET
        - id: member-team-update
          uri: http://${TEAM_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/api/teams/update/**
            - Method=PUT
        - id: member-team-delete
          uri: http://${TEAM_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/api/teams/deleteBy/**
            - Method=DELETE
        - id: assignment-service
          uri: http://${ASSIGNMENT_SERVICE_BASEURL:localhost:8084}
          predicates:
            - Path=/api/assignments/add
            - Method=POST
        - id: assignment-service-all
          uri: http://${ASSIGNMENT_SERVICE_BASEURL:localhost:8084}
          predicates:
            - Path=/api/assignments/get/all
            - Method=GET
        - id: assignment-service-get
          uri: http://${ASSIGNMENT_SERVICE_BASEURL:localhost:8084}
          predicates:
            - Path=/api/assignments/getAssignmentByCode/{assignmentCode}
            - Method=GET
        - id: assignment-service-get
          uri: http://${ASSIGNMENT_SERVICE_BASEURL:localhost:8084}
          predicates:
            - Path=/api/assignments/getByTaskCode/{taskCode}
            - Method=GET
        - id: assignment-service-get
          uri: http://${ASSIGNMENT_SERVICE_BASEURL:localhost:8084}
          predicates:
            - Path=/api/assignments/getByRNumber/{rNumber}
        - id: assignment-service-update
          uri: http://${ASSIGNMENT_SERVICE_BASEURL:localhost:8084}
          predicates:
            - Path=/api/assignments/update/{assignmentCode}
            - Method=PUT
        - id: assignment-service-delete
          uri: http://${ASSIGNMENT_SERVICE_BASEURL:localhost:8084}
          predicates:
            - Path=/api/assignments/delete/{assignmentCode}
            - Method=DELETE

